Repository vansh-codes/ChaosWeb, pull requests merged in 2024-10, with the labels that each got.

#27 Update README.md
  README.md
Labels: hacktoberfest, hacktoberfest-accepted

#30 Created Chaotic Navbar, Contact Us page and Chaotic Timeline of Chaotic Events
  ContactUs.html
  Timeline.html
  css/contactus.css
  css/style.css
  index.html
  js/script.js
  testing.html
Labels: enhancement, gssoc-ext, level3, hacktoberfest, hacktoberfest-accepted, chaos

#37 added random color generation and modified contact page
  js/script.js
Labels: enhancement, gssoc-ext, level2, hacktoberfest, hacktoberfest-accepted

#36 Auto-comment #3
  .github/workflows/autocomment-issue-open-closed.yml
  .github/workflows/preview.yml
Labels: documentation, gssoc-ext, level1, hacktoberfest, hacktoberfest-accepted, ready to merge🎉

#41 Update timeline page and fix animation #34
  Timeline.html
Labels: enhancement, gssoc-ext, level1, hacktoberfest, hacktoberfest-accepted

#65 Time reactive ui #9
  assets/moon1.png
  assets/moon2.png
  index.html
  js/night_time.js
  night_time.html
  style1.css
Labels: enhancement, gssoc-ext, hacktoberfest, hacktoberfest-accepted, chaos, later

#66 added changes after pr review #9
  ContactUs.html
  index.html
  js/night_time.js
Labels: gssoc-ext, level1

#73 rendered favicon and images properly
  css/style.css
  index.html
Labels: bug, gssoc-ext, level1, hacktoberfest, hacktoberfest-accepted

#78 Converted whole project to React js.
  chaosweb-v@2/.gitignore
  chaosweb-v@2/README.md
  chaosweb-v@2/eslint.config.js
  chaosweb-v@2/index.html
  chaosweb-v@2/package-lock.json
  chaosweb-v@2/package.json
  chaosweb-v@2/public/assets/js/night_time.js
  chaosweb-v@2/public/assets/js/script.js
  chaosweb-v@2/public/assets/js/sound.js
  chaosweb-v@2/public/assets/logo/ChaosWeb.jpg
  chaosweb-v@2/public/assets/logo/ChaosWeb.png
  chaosweb-v@2/public/assets/logo/ChaosWeb.svg
  chaosweb-v@2/public/assets/logo/ChaosWeb.tiff
  chaosweb-v@2/public/assets/logo/ChaosWeb.webp
  chaosweb-v@2/public/assets/logo/favicon.ico
  chaosweb-v@2/public/assets/react.svg
  chaosweb-v@2/public/vite.svg
  chaosweb-v@2/src/App.css
  chaosweb-v@2/src/App.jsx
  chaosweb-v@2/src/assets/logo/ChaosWeb.jpg
  chaosweb-v@2/src/assets/logo/ChaosWeb.png
  chaosweb-v@2/src/assets/logo/ChaosWeb.svg
  chaosweb-v@2/src/assets/logo/ChaosWeb.tiff
  chaosweb-v@2/src/assets/logo/ChaosWeb.webp
  chaosweb-v@2/src/assets/logo/favicon.ico
  chaosweb-v@2/src/assets/react.svg
  chaosweb-v@2/src/components/navbar.css
  chaosweb-v@2/src/components/navbar.jsx
  chaosweb-v@2/src/index.css
  chaosweb-v@2/src/main.jsx
  chaosweb-v@2/src/pages/HypnoticChaos.jsx
  chaosweb-v@2/src/pages/Timeline.css
  chaosweb-v@2/src/pages/contact.css
  chaosweb-v@2/src/pages/contact.jsx
  chaosweb-v@2/src/pages/home.jsx
  chaosweb-v@2/src/pages/timeline.jsx
  chaosweb-v@2/vite.config.js
Labels: enhancement, gssoc-ext, level3, hacktoberfest, hacktoberfest-accepted, chaos, migrate

#77 Responsive Search Bar With Logo Problem Fixed
  css/style.css
  index.html
  js/searchbar.js
  sfx/eagle-squawking-type-2-235997.mp3
  sfx/mixkit-annoyed-big-dog-barking-51.wav
  sfx/mixkit-scared-horse-neighing-85.wav
  sfx/mixkit-sweet-kitty-meow-93.wav
Labels: enhancement, gssoc-ext, level2, hacktoberfest, hacktoberfest-accepted, chaos

#80 #46 , #47 added reverse maze and contributors github profile
  README.md
  index.html
  maze.html
Labels: enhancement, gssoc-ext, level2, hacktoberfest, hacktoberfest-accepted, chaos

#64 added a moving gradient bg
  css/style.css
Labels: gssoc-ext, level1, hacktoberfest, hacktoberfest-accepted

#81 update UI of testing page
  testing.html
Labels: enhancement, gssoc-ext, level1, hacktoberfest, hacktoberfest-accepted, chaos

#87 alignment fixed in the contact us page.
  chaosweb-v@2/src/pages/contact.css
  chaosweb-v@2/src/pages/contact.jsx
Labels: enhancement, gssoc-ext, level1, hacktoberfest, hacktoberfest-accepted, chaos

#88 changes some css
  chaosweb-v@2/src/assets/logo/logo.png
  chaosweb-v@2/src/components/navbar.css
  chaosweb-v@2/src/components/navbar.jsx
  node_modules/.yarn-integrity
  package-lock.json
  yarn.lock
Labels: question

#107 Added vibrant color elements, border at the top and changed main heading's font style to make it more chaotic
  assets/logo/chaosweb_topborder-removebg.png
  css/style.css
  index.html
Labels: enhancement, gssoc-ext, level2, hacktoberfest, hacktoberfest-accepted, chaos, ready to merge🎉

#90 Added Mystery Popup (Treasure)
  chaosweb-v@2/src/assets/hamsterSound.mp3
  chaosweb-v@2/src/assets/monkey.jpg
  chaosweb-v@2/src/components/navbar.jsx
  chaosweb-v@2/src/components/popup.jsx
Labels: enhancement, gssoc-ext, level2, hacktoberfest, hacktoberfest-accepted, chaos, ready to merge🎉

#102 Updated LICENSE Link in README.md file
  README.md
Labels: documentation, gssoc-ext, hacktoberfest, hacktoberfest-accepted, ready to merge🎉, level0

#104 Styled the vertical scrollbar.
  preloaderStyle.css
Labels: enhancement, gssoc-ext, level1, chaos, ready to merge🎉

#94 Update README.md
  README.md
Labels: documentation, gssoc-ext, level1, hacktoberfest, hacktoberfest-accepted, chaos

#110 Update ContactUs.html(Changed the UI of contact us page)
  ContactUs.html
Labels: enhancement, gssoc-ext, level1, hacktoberfest, hacktoberfest-accepted, chaos

#116 responsive review section added
  chaosweb-v@2/package-lock.json
  chaosweb-v@2/package.json
  chaosweb-v@2/src/App.jsx
  chaosweb-v@2/src/assets/boy1.jpeg
  chaosweb-v@2/src/assets/boy2.jpeg
  chaosweb-v@2/src/assets/boy3.jpeg
  chaosweb-v@2/src/assets/girl1.jpeg
  chaosweb-v@2/src/assets/girl2.jpeg
  chaosweb-v@2/src/assets/logo/boy2.jpeg
  chaosweb-v@2/src/components/navbar.jsx
  chaosweb-v@2/src/pages/Review.jsx
  chaosweb-v@2/src/pages/review.css
Labels: enhancement, gssoc-ext, level3, hacktoberfest, hacktoberfest-accepted, chaos

#121 Added chaos movement in the About us page!!
  chaosweb-v@2/src/App.jsx
  chaosweb-v@2/src/pages/Contributors.css
  chaosweb-v@2/src/pages/Contributors.jsx
Labels: changes requested

#119 Feature random navigate, Auto-Redirect to random pages
  chaosweb-v@2/src/components/navbar.jsx
  chaosweb-v@2/src/pages/HypnoticChaos.jsx
  chaosweb-v@2/src/pages/Review.jsx
  chaosweb-v@2/src/pages/contact.jsx
  chaosweb-v@2/src/pages/timeline.jsx
  chaosweb-v@2/src/utils/pages.js
Labels: enhancement, gssoc-ext, level1, hacktoberfest, hacktoberfest-accepted, chaos

#129 Added Simon game[new feature]
  Simongame.html
  css/styles.css
  index.html
  js/script1.js
Labels: enhancement, gssoc-ext, level2, hacktoberfest-accepted, chaos

#131 5 webpages were made Responsive
  ContactUs.html
  hypnotic.html
  maze.html
  night_time.html
  style1.css
  testing.html
Labels: enhancement, gssoc-ext, level2, hacktoberfest-accepted, chaos

#136 Added Emoji-Land Feature section (Issue #132)
  emojiland.html
  index.html
  sfx/Emoji-Land/digital-chaos.mp3
  sfx/Emoji-Land/drammatic-cinematic-glitch.mp3
  sfx/Emoji-Land/electric-wasps.mp3
  sfx/Emoji-Land/glitch-sound.mp3
  sfx/Emoji-Land/hurricane.mp3
  sfx/Emoji-Land/intro-music-black-box-dirty-glitch.mp3
Labels: enhancement, gssoc-ext, level2, hacktoberfest-accepted, chaos

#135 added a new signin and signup page
  3d-effect-hypnosis-spiral-vector-7844424.jpg
  chaos.html
  index.html
  signup.html
Labels: enhancement, gssoc-ext, level2, hacktoberfest-accepted, chaos

#138 scroll bar added : Scroll bar added #133 done
  chaosweb-v@2/src/index.css
Labels: enhancement, gssoc-ext, level1, hacktoberfest-accepted, chaos

#117 Maze Game and Inverted color
  IMG_20241015_121622.jpg
  assets/mazeIcon.png
  chaosweb-v@2/src/App.jsx
  chaosweb-v@2/src/components/InvertColorToggle.jsx
  chaosweb-v@2/src/components/MazeGame.css
  chaosweb-v@2/src/components/MazeGame.jsx
  chaosweb-v@2/src/components/navbar.css
  chaosweb-v@2/src/components/navbar.jsx
  chaosweb-v@2/src/index.css
  package-lock.json
Labels: enhancement, gssoc-ext, level3, hacktoberfest-accepted, chaos, conflicts, Reactv2

#148 Added ChaosMania and ButtonCollections and added multiple chaotic reusable components
  chaosweb-v@2/package-lock.json
  chaosweb-v@2/package.json
  chaosweb-v@2/postcss.config.js
  chaosweb-v@2/src/App.jsx
  chaosweb-v@2/src/assets/snowstruct.png
  chaosweb-v@2/src/components/FireRain.css
  chaosweb-v@2/src/components/FireRain.jsx
  chaosweb-v@2/src/components/Firework.css
  chaosweb-v@2/src/components/Firework.jsx
  chaosweb-v@2/src/components/FloatingRain.css
  chaosweb-v@2/src/components/FloatingRain.jsx
  chaosweb-v@2/src/components/Snowfall.css
  chaosweb-v@2/src/components/Snowfall.jsx
  chaosweb-v@2/src/components/Starfield.css
  chaosweb-v@2/src/components/Starfield.jsx
  chaosweb-v@2/src/components/navbar.jsx
  chaosweb-v@2/src/index.css
  chaosweb-v@2/src/pages/ButtonCollection.css
  chaosweb-v@2/src/pages/ButtonCollection.jsx
  chaosweb-v@2/src/pages/ChaosMania.css
  chaosweb-v@2/src/pages/ChaosMania.jsx
  chaosweb-v@2/tailwind.config.js
Labels: enhancement, gssoc-ext, level3, hacktoberfest-accepted, chaos, Reactv2

#154 Remove horizontal scroll
  chaosweb-v@2/src/components/navbar.css
  chaosweb-v@2/src/components/navbar.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level0

#162 Added a chaotic title
  chaosweb-v@2/index.html
  chaosweb-v@2/package-lock.json
  chaosweb-v@2/public/logo.png
  chaosweb-v@2/public/vite.svg
Labels: enhancement, gssoc-ext, level1, hacktoberfest-accepted, chaos

#165 Feat:Implemented Bouncing Div with DVD Logo
  chaosweb-v@2/src/pages/BouncingDiv.jsx
  chaosweb-v@2/src/pages/home.jsx
Labels: enhancement, gssoc-ext, level2, hacktoberfest-accepted, chaos, Reactv2

#168 Animation input contact
  ContactUs.html
  js/script.js
Labels: enhancement, gssoc-ext, level1, hacktoberfest-accepted, chaos

#181 Done the enhancements and also addded some new sections
  CONTRIBUTING.md
Labels: documentation, gssoc-ext, level1, chaos

#166 Solid Colored Cards on Timeline Page Affecting UI #100
  Timeline.html
  css/styles.css
Labels: enhancement, gssoc-ext, level1, chaos

#191 Word Guessing Game
  WordGuessingGame.html
  index.html
Labels: enhancement, gssoc-ext, level1, chaos

#188 Chaotic Feat: Add Parallax Scrolling Effect
  assets/Order And Chaos.png
  assets/colourfulbg.png
  assets/crayonbg.png
  chaosweb-v@2/index.html
  chaosweb-v@2/style.css
Labels: enhancement, gssoc-ext, level1, chaos

#197 Chaotic Feat: Added Barrell Roll Functionality
  chaosweb-v@2/src/App.jsx
  chaosweb-v@2/src/components/navbar.jsx
  chaosweb-v@2/src/pages/BarrelRoll.css
  chaosweb-v@2/src/pages/BarrelRoll.jsx
  chaosweb-v@2/src/pages/home.jsx
Labels: enhancement, gssoc-ext, level1, hacktoberfest-accepted, chaos, Reactv2

#200 chaosssss text animated
  chaosweb-v@2/index.html
Labels: enhancement, gssoc-ext, level1, chaos

#201 Chaotic Feat: Glassmorphism Effect
  css/contactus.css
Labels: enhancement, gssoc-ext, level1, chaos

#203 Automated of project structure updation using GitHub workflows and Python scripts
  .github/scripts/update_structure.py
  .github/workflows/update-readme.yml
  CONTRIBUTING.md
  PROJECT_STRUCTURE.md
  README.md
  repo_structure.txt
Labels: documentation, gssoc-ext, level3, hacktoberfest-accepted, chaos

#204 I have updated the file and chnaged the desired baground.
  chaosweb-v@2/index.html
Labels: hacktoberfest, hacktoberfest-accepted

#207 Chaotic Feat: Added Rate Us Feature
  chaosweb-v@2/package-lock.json
  chaosweb-v@2/package.json
  chaosweb-v@2/src/App.jsx
  chaosweb-v@2/src/components/navbar.jsx
  chaosweb-v@2/src/pages/BarrelRoll.css
  chaosweb-v@2/src/pages/RateUs.css
  chaosweb-v@2/src/pages/RateUs.jsx
Labels: enhancement, gssoc-ext, level2, hacktoberfest-accepted, chaos, Reactv2

#210 Chaotic Feature: Feature add effects
  chaosweb-v@2/src/App.jsx
  chaosweb-v@2/src/components/navbar.jsx
  chaosweb-v@2/src/pages/ColorEffect.css
  chaosweb-v@2/src/pages/TestEffects.jsx
Labels: enhancement, gssoc-ext, level1, hacktoberfest-accepted, chaos, Reactv2
