Repository vansh-codes/ChaosWeb, pull requests merged in 2024-11, with the labels that each got.

#221 hactoberfest image change in readme.md
  README.md
Labels: documentation, gssoc-ext, chaos, level0

#223 Chaotic Visuals
  Sample.html
  index.html
Labels: enhancement, gssoc-ext, level2, chaos

#225 Chaos
  egg.html
  index.html
Labels: enhancement, gssoc-ext, level2, chaos

#228 Chaos Typing Universe
  chaosweb-v@2/package-lock.json
  chaosweb-v@2/package.json
  chaosweb-v@2/src/App.jsx
  chaosweb-v@2/src/pages/ChaoticTypingTest.css
  chaosweb-v@2/src/pages/ChaoticTypingTest.jsx
  chaosweb-v@2/src/utils/pages.js
Labels: enhancement, level1, chaos, Reactv2
